routes/web.php
<?php

use App\Http\Controllers\KatagoriController;
use App\Http\Controllers\ProdukController;
use App\Http\Controllers\SupplierController;
use App\Http\Controllers\PengeluaranController;
use App\Http\Controllers\PembelianController;
use App\Http\Controllers\PembelianDetailController;
use App\Http\Controllers\PenjualanController;
use App\Http\Controllers\PenjualanDetailController;
use App\Http\Controllers\MemberController;
use App\Http\Controllers\SettingController; 
use App\Http\Controllers\LaporanController; 
use App\Http\Controllers\UserController; 
use App\Http\Controllers\DashboardController; 
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

// no fix there is one problem on '=>'
// fungsi ini akan meredirect ke halaman login
// Route::get('/', fn () => redirect()->route('login'));

// fix
// !fungsi ini akan meredirect ke halaman login
Route::get('/', function () {
    return redirect()->route('login');
});
Route::group(['middleware' => 'auth'], function(){
    // ini akan mengembalikan ke halaman home.blade.php yang di extends dari file master.blade.php
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');

    // ! route ini hanya bisa di akses oleh admin
    Route::group(['middleware' => 'level:1'], function () {
        Route::get('/katagori/data', [KatagoriController::class, 'data'])->name('katagori.data');
        Route::resource('/katagori', KatagoriController::class);
    
        Route::get('/produk/data', [ProdukController::class, 'data'])->name('produk.data');
        Route::post('/produk/delete_selected', [ProdukController::class, 'deleteSelected'])->name('produk.delete_selected');
        Route::resource('/produk', ProdukController::class);

        // ! Route ini akan mengakses method create yang ada pada MemberController
        Route::get('/member/data', [MemberController::class, 'data'])->name('member.data');
        Route::post('/member/delete_selected', [MemberController::class, 'deleteSelected'])->name('member.delete_selected');
        Route::resource('/member', MemberController::class);
    
        Route::get('/supplier/data', [SupplierController::class, 'data'])->name('supplier.data');
        Route::resource('/supplier', SupplierController::class);
    
        Route::get('/pengeluaran/data', [PengeluaranController::class, 'data'])->name('pengeluaran.data');
        Route::resource('/pengeluaran', PengeluaranController::class);
    
        Route::get('/pembelian/data', [PembelianController::class, 'data'])->name('pembelian.data');
        Route::get('/pembelian/{id}/create', [PembelianController::class, 'create'])->name('pembelian.create');
        Route::resource('/pembelian', PembelianController::class)
            ->except('create');
    
        Route::get('/pembelian_detail/{id}/data', [PembelianDetailController::class, 'data'])->name('pembelian_detail.data');
        Route::get('/pembelian_detail/loadform/{diskon}/{total}', [PembelianDetailController::class, 'loadForm'])->name('pembelian_detail.load_form');
        Route::resource('/pembelian_detail', PembelianDetailController::class)
        ->except('create', 'show', 'edit');
    
        Route::get('/penjualan/data', [PenjualanController::class, 'data'])->name('penjualan.data');
        Route::get('/penjualan', [PenjualanController::class, 'index'])->name('penjualan.index');
        Route::get('/penjualan/{id}', [PenjualanController::class, 'show'])->name('penjualan.show');
        Route::delete('/penjualan/{id}', [PenjualanController::class, 'destroy'])->name('penjualan.destroy');// ! ini akan mendelete transaksi
    });



    // ! route ini hanya bisa di akses oleh kasir
    Route::group(['middleware' => 'level:2'], function () {
        // ! Route ini akan mengakses method create yang ada pada PenjualanController
        Route::get('/transaksi/baru', [PenjualanController::class, 'create'])->name('transaksi.baru');
        Route::post('/transaksi/simpan', [PenjualanController::class, 'store'])->name('transaksi.simpan');
        Route::get('/transaksi/selesai', [PenjualanController::class, 'selesai'])->name('transaksi.selesai');
        Route::get('/transaksi/nota-kecil', [PenjualanController::class, 'notaKecil'])->name('transaksi.nota_kecil');
        Route::get('/transaksi/nota-besar', [PenjualanController::class, 'notaBesar'])->name('transaksi.nota_besar');


        Route::get('/transaksi/{id}/data', [PenjualanDetailController::class, 'data'])->name('transaksi.data');
        Route::get('/transaksi/loadform/{id}/{total}/{diterima}', [PenjualanDetailController::class, 'loadForm'])->name('transaksi.load_form');
        Route::resource('/transaksi', PenjualanDetailController::class)
        ->except('create', 'show', 'edit');
    });

    
    
    // ! route ini hanya bisa di akses oleh admin
    Route::group(['middleware' => 'level:1'], function () {
        Route::get('/setting', [SettingController::class, 'index'])->name('setting.index');
        Route::get('/setting/first', [SettingController::class, 'show'])->name('setting.show');
        Route::post('/setting', [SettingController::class, 'update'])->name('setting.update');
        
        Route::get('/laporan', [LaporanController::class, 'index'])->name('laporan.index');
        Route::get('/laporan/data/{awal}/{akhir}', [LaporanController::class, 'data'])->name('laporan.data');
        Route::get('/laporan/pdf/{awal}/{akhir}', [LaporanController::class, 'exportPDF'])->name('laporan.export_pdf');

        Route::get('/user/data', [UserController::class, 'data'])->name('user.data');
        Route::resource('/user', UserController::class);
    });



    // ! route ini bisa di akses oleh admin dan kasir
    Route::group(['middleware' => 'level:1,2'], function () {
        Route::get('/profile', [UserController::class, 'profile'])->name('user.profile');
        Route::post('/profile', [UserController::class, 'updateProfile'])->name('user.update_profile');
    });

});
// Route::middleware([
//     'auth:sanctum',
//     config('jetstream.auth_session'),
//     'verified'
// ])->group(function () {
//     // route ini mengakses pada views/dashboard.blade.php
//     Route::get('/dashboard', function () {
//         return view('home');
//     })->name('dashboard');
// });

resources/views/admin/dashboard.blade.php
@extends('layouts.master')

@section('title')
    Dashboard
@endsection

@section('breadcrumb')
    @parent
    <li class="active">Dashboard</li>
@endsection

@section('content')
<!-- Small boxes (Stat box) -->
<div class="row">
    <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-aqua">
            <div class="inner">
                <h3>{{ $katagori }}</h3>
                <p>Total Katagori</p>
            </div>
            <div class="icon">
                <i class="fa fa-cube"></i>
            </div>
            {{-- ! ini kana back ke menu katagori --}}
            <a href="{{ route('katagori.index') }}" class="small-box-footer">Lihat Detail<i class="fa fa-arrow-circle-right"></i></a>
        </div>
    </div>
    <!-- ./col -->
    <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-green">
            <div class="inner">
                <h3>{{ $produk }}</h3>
                <p>Total Produk</p>
            </div>
            <div class="icon">
                <i class="fa fa-cubes"></i>
            </div>
            {{-- ! ini kana back ke menu produk --}}
            <a href="{{ route('produk.index') }}" class="small-box-footer">Lihat Detail<i class="fa fa-arrow-circle-right"></i></a>
        </div>
    </div>
    <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-yellow">
            <div class="inner">
                <h3>{{ $pembelian }}</h3>
                <p>Total Pembelian</p>
            </div>
            <div class="icon">
                <i class="fa fa-money"></i>
            </div>
            {{-- ! ini kana back ke menu supplier --}}
            <a href="{{ route('pembelian.index') }}" class="small-box-footer">Lihat Detail<i class="fa fa-arrow-circle-right"></i></a>
        </div>
    </div>
    <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-red">
            <div class="inner">
                <h3>{{ $penjualan }}</h3>
                <p>Total Penjualan</p>
            </div>
            <div class="icon">
                <i class="fa fa-pie-chart"></i>
            </div>
            {{-- ! ini kana back ke menu supplier --}}
            <a href="{{ route('penjualan.index') }}" class="small-box-footer">Lihat Detail<i class="fa fa-arrow-circle-right"></i></a>
        </div>
    </div>
    <!-- ./col -->
</div>
<!-- /.row -->
<!-- Main row -->
<div class="row">
    <div class="col-lg-12">
        <div class="box">
            <div class="box-header with-border">
                <div class="text-center">
                    {{-- menampilkan total pendapatan sesuai tanggal awal-akhir --}}
                <h3 class="box-title" class="box-title" style="margin-auto">Grafik Pendapatan {{ tanggal_indo($tanggal_awal) }} s/d {{ tanggal_indo($tanggal_akhir) }}</h3>
                </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="chart">
                            <!-- Sales Chart Canvas -->
                            <canvas id="salesChart" style="height: 180px;"></canvas>
                        </div>
                        <!-- /.chart-responsive -->
                    </div>
                </div>
                <!-- /.row -->
            </div>
        </div>
        <!-- /.box -->
    </div>
    <!-- /.col -->
</div>
<!-- /.row (main row) -->
<!-- Pop-up Alert -->
<div class="custom-popup text-center">
    <div class="popup-content">
        <h2>Selamat Datang di Halaman Dashboard</h2>
        <h4>Anda Login Sebagai Owner.</h4>
    </div>
</div>
@endsection

@push('scripts')
<!-- ChartJS -->
<script src="{{ asset('AdminLTE/bower_components/chart.js/Chart.js') }}"></script>
<script>
$(function() {
    // Display a welcome alert
    alert("Selamat Datang Di Halaman Dashboard PosKu");
    // Get context with jQuery - using jQuery's .get() method.
    var salesChartCanvas = $('#salesChart').get(0).getContext('2d');
    // This will get the first returned node in the jQuery collection.
    var salesChart = new Chart(salesChartCanvas);

    var salesChartData = {
        labels: {{ json_encode($data_tanggal) }},
        datasets: [
            {
                label: 'Pendapatan',
                fillColor           : 'rgba(60,141,188,0.9)',
                strokeColor         : 'rgba(60,141,188,0.8)',
                pointColor          : '#3b8bba',
                pointStrokeColor    : 'rgba(60,141,188,1)',
                pointHighlightFill  : '#fff',
                pointHighlightStroke: 'rgba(60,141,188,1)',
                data: {{ json_encode($data_pendapatan) }}
            }
        ]
    };

    var salesChartOptions = {
        pointDot : false,
        responsive : true
    };

    salesChart.Line(salesChartData, salesChartOptions);
});
</script>
@endpush