routes/web.php
<?php

use App\Http\Controllers\KatagoriController;
use App\Http\Controllers\ProdukController;
use App\Http\Controllers\SupplierController;
use App\Http\Controllers\PengeluaranController;
use App\Http\Controllers\PembelianController;
use App\Http\Controllers\PembelianDetailController;
use App\Http\Controllers\PenjualanController;
use App\Http\Controllers\PenjualanDetailController;
use App\Http\Controllers\MemberController;
use App\Http\Controllers\SettingController; 
use App\Http\Controllers\LaporanController; 
use App\Http\Controllers\UserController; 
use App\Http\Controllers\DashboardController; 
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

// no fix there is one problem on '=>'
// fungsi ini akan meredirect ke halaman login
// Route::get('/', fn () => redirect()->route('login'));

// fix
// !fungsi ini akan meredirect ke halaman login
Route::get('/', function () {
    return redirect()->route('login');
});
Route::group(['middleware' => 'auth'], function(){
    // ini akan mengembalikan ke halaman home.blade.php yang di extends dari file master.blade.php
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');

    // ! route ini hanya bisa di akses oleh admin
    Route::group(['middleware' => 'level:1'], function () {
        Route::get('/katagori/data', [KatagoriController::class, 'data'])->name('katagori.data');
        Route::resource('/katagori', KatagoriController::class);
    
        Route::get('/produk/data', [ProdukController::class, 'data'])->name('produk.data');
        Route::post('/produk/delete_selected', [ProdukController::class, 'deleteSelected'])->name('produk.delete_selected');
        Route::resource('/produk', ProdukController::class);

        // ! Route ini akan mengakses method create yang ada pada MemberController
        Route::get('/member/data', [MemberController::class, 'data'])->name('member.data');
        Route::post('/member/delete_selected', [MemberController::class, 'deleteSelected'])->name('member.delete_selected');
        Route::resource('/member', MemberController::class);
    
        Route::get('/supplier/data', [SupplierController::class, 'data'])->name('supplier.data');
        Route::resource('/supplier', SupplierController::class);
    
        Route::get('/pengeluaran/data', [PengeluaranController::class, 'data'])->name('pengeluaran.data');
        Route::resource('/pengeluaran', PengeluaranController::class);
    
        Route::get('/pembelian/data', [PembelianController::class, 'data'])->name('pembelian.data');
        Route::get('/pembelian/{id}/create', [PembelianController::class, 'create'])->name('pembelian.create');
        Route::resource('/pembelian', PembelianController::class)
            ->except('create');
    
        Route::get('/pembelian_detail/{id}/data', [PembelianDetailController::class, 'data'])->name('pembelian_detail.data');
        Route::get('/pembelian_detail/loadform/{diskon}/{total}', [PembelianDetailController::class, 'loadForm'])->name('pembelian_detail.load_form');
        Route::resource('/pembelian_detail', PembelianDetailController::class)
        ->except('create', 'show', 'edit');
    
        Route::get('/penjualan/data', [PenjualanController::class, 'data'])->name('penjualan.data');
        Route::get('/penjualan', [PenjualanController::class, 'index'])->name('penjualan.index');
        Route::get('/penjualan/{id}', [PenjualanController::class, 'show'])->name('penjualan.show');
        Route::delete('/penjualan/{id}', [PenjualanController::class, 'destroy'])->name('penjualan.destroy');// ! ini akan mendelete transaksi
    });



    // ! route ini hanya bisa di akses oleh kasir
    Route::group(['middleware' => 'level:2'], function () {
        // ! Route ini akan mengakses method create yang ada pada PenjualanController
        Route::get('/transaksi/baru', [PenjualanController::class, 'create'])->name('transaksi.baru');
        Route::post('/transaksi/simpan', [PenjualanController::class, 'store'])->name('transaksi.simpan');
        Route::get('/transaksi/selesai', [PenjualanController::class, 'selesai'])->name('transaksi.selesai');
        Route::get('/transaksi/nota-kecil', [PenjualanController::class, 'notaKecil'])->name('transaksi.nota_kecil');
        Route::get('/transaksi/nota-besar', [PenjualanController::class, 'notaBesar'])->name('transaksi.nota_besar');


        Route::get('/transaksi/{id}/data', [PenjualanDetailController::class, 'data'])->name('transaksi.data');
        Route::get('/transaksi/loadform/{id}/{total}/{diterima}', [PenjualanDetailController::class, 'loadForm'])->name('transaksi.load_form');
        Route::resource('/transaksi', PenjualanDetailController::class)
        ->except('create', 'show', 'edit');
    });

    
    
    // ! route ini hanya bisa di akses oleh admin
    Route::group(['middleware' => 'level:1'], function () {
        Route::get('/setting', [SettingController::class, 'index'])->name('setting.index');
        Route::get('/setting/first', [SettingController::class, 'show'])->name('setting.show');
        Route::post('/setting', [SettingController::class, 'update'])->name('setting.update');
        
        Route::get('/laporan', [LaporanController::class, 'index'])->name('laporan.index');
        Route::get('/laporan/data/{awal}/{akhir}', [LaporanController::class, 'data'])->name('laporan.data');
        Route::get('/laporan/pdf/{awal}/{akhir}', [LaporanController::class, 'exportPDF'])->name('laporan.export_pdf');

        Route::get('/user/data', [UserController::class, 'data'])->name('user.data');
        Route::resource('/user', UserController::class);
    });



    // ! route ini bisa di akses oleh admin dan kasir
    Route::group(['middleware' => 'level:1,2'], function () {
        Route::get('/profile', [UserController::class, 'profile'])->name('user.profile');
        Route::post('/profile', [UserController::class, 'updateProfile'])->name('user.update_profile');
    });

});
// Route::middleware([
//     'auth:sanctum',
//     config('jetstream.auth_session'),
//     'verified'
// ])->group(function () {
//     // route ini mengakses pada views/dashboard.blade.php
//     Route::get('/dashboard', function () {
//         return view('home');
//     })->name('dashboard');
// });

app/Models/Katagori.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Katagori extends Model
{
    use HasFactory;

    protected $table = 'katagori';
    protected $primaryKey = 'id_katagori';
    protected $guarded = [];
}

app/Http/Controllers/KatagoriController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Katagori;

class KatagoriController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        return view('katagori.index');
    }
    public function data(){
        $katagori = Katagori::orderBy('id_katagori', 'desc')->get();
        
            return datatables()
            ->of($katagori)
            ->addIndexColumn()
            ->addColumn('aksi', function ($katagori) {
                return '
                <div class="btn-group">
                    <button onclick="editForm(`'. route('katagori.update', $katagori->id_katagori) .'`)" 
                    class="btn btn-xs btn-warning btn-flat">
                    <i class="fa fa-pencil"></i><i>Ubah</i>
                    </button>
                    <button onclick="deleteData(`'. route('katagori.destroy', $katagori->id_katagori) .'`)" 
                    class="btn btn-xs btn-danger btn-flat">
                    <i class="fa fa-trash"></i><i>Hapus</i>
                    </button>
                </div>
                ';
            })
            ->rawColumns(['aksi'])
            ->make(true);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $katagori = new Katagori();
        $katagori->nama_katagori = $request->nama_katagori;
        $katagori->save();

        return response()->json('Data Berhasil Disimpan', 200);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $katagori = Katagori::find($id);

        return response()->json($katagori);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $katagori = Katagori::find($id);
        $katagori->nama_katagori = $request->nama_katagori;
        $katagori->update();

        return response()->json('Data Berhasil Disimpan', 200);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $katagori = Katagori::find($id);
        $katagori->delete();

        return response(null, 204);
    }
}

resources/views/katagori/form.blade.php
  <div class="modal fade" id="modal-form" tabindex="-1" role="dialog" aria-labelledby="modal-form">
    <div class="modal-dialog" role="document">
      <form action="" method="post" class="form-horizontal">
        @csrf
        @method('post')

        <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title"></h4>
            </div>
            <div class="modal-body">
              <div class="form-group row">
                <label for="nama_katagori" class="col-md-2 col-md-offset-1 control-label">Katagori</label>
                <div class="col-md-9">
                    <input type="text" name="nama_katagori" id="nama_katagori" class="form-control" required autofocus>
                    <span class="help-block with-errors"></span>
                </div>
              </div>
            </div>
            <div class="modal-footer">
                <button class="btn btn-sm btn-flat btn-primary">Simpan</button>
                <button type="button" class="btn btn-sm btn-flat btn-default" data-dismiss="modal">Batal</button>
            </div>
          </div>
      </form>
    </div>
  </div>

resources/views/katagori/index.blade.php
{{-- Untuk mengakses layouts halaman utama dari layouts.master --}}
@extends('layouts.master')

@section('title')
    Daftar Katagori
@endsection

@section('breadcrumb')
    @parent
    <li class="active">Daftar Katagori</li>
@endsection

@section('content')
                        <div class="row">
                            <div class="col-md-12">
                              <div class="box">
                                <div class="box-header with-border">
                                  <button onclick="addForm('{{ route('katagori.store') }}')" class="btn btn-success btn-xs btn-flat"><i class="fa fa-plus-circle"></i>Tambah</button>
                                </div>
                                {{-- ini ketika di akases menggunakan perangkat device akan responsive karena menggunakan table-responsive --}}
                                <div class="box-body table-responsive">
                                    <table class="table table-stiped table-bordered">
                                        <thead>
                                            <th width="5%">No</th>
                                            <th>Katagori</th>
                                            <th width="15%"><i class="fa fa-cog"></i></th>
                                        </thead>
                                        <tbody></tbody>
                                    </table>
                                </div>
                              </div>
                            </div>
                          </div>

@includeIf('katagori.form')
@endsection

@push('scripts')
    <script>
        let table;
        $(function (){
            table = $('.table').DataTable({
                processing: true,
                autoWidth: false,
                ajax: {
                    url: '{{ route('katagori.data') }}',
                },
                columns: [
                    // ini akan menampilakn kolom pada tabel katagori
                    {data: 'DT_RowIndex', searchable: false, sortable: false},
                    {data: 'nama_katagori'},
                    {data: 'aksi', searchable: false, sortable: false},
                ]
            });
            $('#modal-form').validator().on('submit', function (e) {
                if (! e.preventDefault()) {
                    $.post($('#modal-form form').attr('action'), $('#modal-form form').serialize())
                    .done((response) => {
                        $('#modal-form').modal('hide');
                        table.ajax.reload();
                    })
                    .fail((errors) => {
                        alert('Tidak Dapat Menyimpan Data');
                        return;
                    });
                }
            });
        });
        // fungsi ini untuk add data baru pada form di tabel katagori
        function addForm(url) {
            $('#modal-form').modal('show');
            $('#modal-form .modal-title').text('Tambah Katagori');

            $('#modal-form form')[0].reset();
            $('#modal-form form').attr('action', url);
            $('#modal-form [name=_method]').val('post');
            $('#modal-form [name=nama_katagori]').focus();
        }
        // fungsi ini untuk mengedit data pada tabel katagori
        function editForm(url) {
            $('#modal-form').modal('show');
            $('#modal-form .modal-title').text('Edit Katagori');

            $('#modal-form form')[0].reset();
            $('#modal-form form').attr('action', url);
            $('#modal-form [name=_method]').val('put');
            $('#modal-form [name=nama_katagori]').focus();

            $.get(url)
            .done((response) => {
                $('#modal-form [name=nama_katagori]').val(response.nama_katagori);
            })
            .fail((error) => {
                alert('Tidak Dapat Menampilkan Data')
            });
        }
        // fungsi ini untuk menghapus 1 data di tabel katagori
        function deleteData(url) {
            if (confirm('Yakin Ingin Menghapus Data Ini?')) {
                $.post(url, {
                '_token': $('[name=csrf-token]').attr('content'),
                '_method': 'delete'
            })
            .done((response) => {
                table.ajax.reload();
            })
            .fail((error) => {
                alert('Tidak Dapat Menghapus Data')
                return;
            });
            }
        }
    </script>
@endpush